name: Reusable php-cs-fixer

on:
  workflow_call:
    inputs:
      php-version:
        type: string
        required: false
        default: "8.1"
    secrets:
      packagist-token:
        required: true

jobs:
  php-cs-fixer:
    name: "php-cs-fixer"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.1"
          extensions: ctype, gd, iconv, imagick, json, pcntl, zip, mariadb
        env:
          COMPOSER_TOKEN: ${{ secrets.packagist-token }}

      - name: Get composer cache directory
        id: composerCache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composerCache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: "Install latest dependencies"
        run: composer install --ansi --no-interaction --no-progress --prefer-dist

      - name: "Run php-cs-fixer"
        run: composer php-cs-fix


